### ISSUE TITLE
Arm/wrist can go through forbidden zone on way to target

### ISSUE THREAD

**Issue by brettle** [DeepBlueRobotics/RobotCode2023#11]
Right now, the code will allow a target to be set as long as it is not in the forbidden zone. However, the arm/wrist could still pass through the forbidden zone on the way to the target, resulting in a collision.

**Comment by brettle** [comment]
In case you are thinking that the fix would be to check the intermediate position (i.e. by simulating running the profile), note that will prevent movement if we are already in a forbidden position. My best suggestion is to only allow wrist movement if it is in a direction that is safe given the current tip position, and only allow arm movement if the tip is not in a forbidden position. These restrictions would be implemented in `driveArm()` and `driveWrist()`. Open to other ideas.

**Comment by CoolSpy3** [comment]
Fixed on master.
